[global]
# Your Spotify account name.
username = andrewdcato

# Your Spotify account password.
password = f%6INtvVzunf3jFaPq9H+W.qC

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = portaudio

proxy = http://localhost:8888/auth
