tap "cloudflare/cloudflare"
tap "esolitos/ipa"
tap "felixkratz/formulae"
tap "hashicorp/tap"
tap "idoavrah/homebrew"
tap "indirect/tap"
tap "jandedobbeleer/oh-my-posh"
tap "khanhas/tap"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "ngrok/ngrok"
tap "nikitabobko/tap"
tap "rigellute/tap"
tap "teamookla/speedtest"

brew "act"
brew "ansible"
brew "ansible-language-server"
brew "ansible-lint"
brew "aom"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bat"
brew "bc"
brew "btop"
brew "caddy"
brew "cask"
brew "coreutils"
brew "curl"
brew "dbus", restart_service: :changed
brew "driftctl"
brew "esolitos/ipa/sshpass"
brew "fastfetch"
brew "fd"
brew "felixkratz/formulae/sketchybar"
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "fontforge"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gdk-pixbuf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-flow-avh"
brew "git-recent"
brew "glib"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "gnutls"
brew "graphviz"
brew "grep"
brew "groff"
brew "gtop"
brew "gts"
brew "harfbuzz"
brew "hashicorp/tap/terraform-ls"
brew "highlight"
brew "hub"
brew "idoavrah/homebrew/tftui"
brew "imagemagick"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jpeg-xl"
brew "jq"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "lazydocker"
brew "lazygit"
brew "libheif"
brew "libpq"
brew "librsvg"
brew "libtool"
brew "libyaml"
brew "lolcat"
brew "lsd"
brew "luarocks"
brew "mackup"
brew "mas"
brew "mongocli"
brew "mongodb/brew/mongodb-community@6.0"
brew "mongosh"
brew "mosh"
brew "neovim"
brew "netpbm"
brew "nghttp2"
brew "nginx"
brew "node"
brew "nowplaying-cli"
brew "nvm"
brew "pkgconf"
brew "pnpm"
brew "poppler"
brew "portaudio"
brew "pyenv"
brew "python@3.10"
brew "ripgrep"
brew "rust"
brew "rustup"
brew "sdl2"
brew "sesh"
brew "sevenzip"
brew "shared-mime-info"
brew "spaceship"
brew "sql-language-server"
brew "starship"
brew "stow"
brew "stylua"
brew "subversion"
brew "switchaudio-osx"
brew "teamookla/speedtest/speedtest"
brew "telnet"
brew "terraform"
brew "terragrunt"
brew "tfenv"
brew "tflint"
brew "tmux"
brew "tokei"
brew "trash"
brew "tree"
brew "tty-clock"
brew "wakeonlan"
brew "webp"
brew "wget"
brew "yamlfmt"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alfred"
cask "balenaetcher"
cask "bartender"
cask "betterdisplay"
cask "bettertouchtool"
cask "chromium"
cask "daisydisk"
cask "dash"
cask "discord"
cask "docker-desktop"
cask "firefox@developer-edition"
cask "flux-app"
cask "forklift"
cask "fujitsu-scansnap-home"
cask "ghostty"
cask "gitify"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "logi-options+"
cask "logitune"
cask "mongodb-compass"
cask "ngrok"
cask "obsidian"
cask "onyx"
cask "pgadmin4"
cask "philips-hue-sync"
cask "plexamp"
cask "postman"
cask "qmk-toolbox"
cask "raspberry-pi-imager"
cask "sf-symbols"
cask "signal"
cask "slack"
cask "steam"
cask "synology-drive"
cask "thunderbird"
cask "utm"
cask "vagrant"
cask "via"
cask "virtualbox"
cask "visual-studio-code"
cask "wezterm"
cask "zoom"

cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspice-nerd-font"
cask "font-noto-sans-symbols-2"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-symbols-only-nerd-font"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Auto HD FPS for YouTube", id: 1546729687
mas "CARROTweather", id: 993487541
mas "Apple Developer", id: 640199958
mas "Fantastical", id: 975937182
mas "Ghostery – Privacy Ad Blocker", id: 1436953057
mas "Home Assistant", id: 1099568401
mas "iStat Mini", id: 927292435
mas "Klack", id: 6446206067
mas "Parcel Classic", id: 639968404
mas "PayPal Honey", id: 1472777122
mas "PocketTube", id: 1533703891
mas "Quiver", id: 866773894
mas "The Unarchiver", id: 425424353
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835

vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "vscodevim.vim"
