local M = {}

M.icons = {
	close = "󰅙 ",
	dir = "󰉋 ",
	lsp = "  ",
	vim = "  ",
	debug = " ",
	files = {
		details = "󱁻 ",
		ruler = "󰱼 ",
	},
	separators = {
		block = "█",
		dotted_vert = "┊",
		double_vert = "║",
		inverted_slant_left = "",
		inverted_slant_right = "",
		rounded_left = "",
		rounded_right = "",
		slant_br = "",
		slant_left = "",
		slant_right = "",
		slant_ur = "",
		vert = "│",
		vert_thick = "┃",
	},
	diagnostics = {
		error = "",
		hint = "",
		info = "",
		warn = "",
		code_action = " ",
	},
	git = {
		added = "",
		branch = "",
		conflict = "",
		deleted = "",
		ignored = "",
		modified = "",
		removed = "",
		renamed = "",
		staged = "",
		unstaged = "",
		untracked = "",
	},
	kinds = {
		Array = "",
		Boolean = "",
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "",
		Function = "",
		Interface = "",
		Key = "",
		Keyword = "",
		Method = "m",
		Module = "",
		Namespace = "",
		Null = "ﳠ",
		Number = "",
		Object = "",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "",
		Snippet = "",
		String = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
	},
}

return M
