require("lazy").setup({
	{ import = "cato.plugins" },
	{ import = "cato.plugins.colorscheme" },
	{ import = "cato.plugins.lsp" },
}, {
	install = {
		missing = true,
		colorscheme = { "catppuccin" },
	},
	ui = {
		border = "rounded",
		size = {
			width = 0.9,
			height = 0.9,
		},
		icons = require("cato.util").icons.lazy,
	},
	performance = {
		rtp = {
			disabled_plugins = {
				"2html_plugin",
				"tohtml",
				"getscript",
				"getscriptPlugin",
				"gzip",
				"logipat",
				"netrw",
				"netrwPlugin",
				"netrwSettings",
				"netrwFileHandlers",
				"matchit",
				"tar",
				"tarPlugin",
				"rrhelper",
				"spellfile_plugin",
				"vimball",
				"vimballPlugin",
				"zip",
				"zipPlugin",
				"tutor",
				"rplugin",
				"syntax",
				"synmenu",
				"optwin",
				"compiler",
				"bugreport",
				"ftplugin",
			},
		},
	},
})
