# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = true 

# Define order to make prompt on one line
# https://starship.rs/config/#default-prompt-order
format = """
$sudo\
$username\
$hostname\
$directory\
$package\
$nodejs\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$cmd_duration\
$line_break\
$jobs\
$status\
$character\
"""

# Change timeout of scanning files to 10 mili secs
scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold blue)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold italic cyan"

[package]
format = 'at [$symbol$version](208 bold) '
symbol = '󰏗 '
display_private = true

[nodejs]
format = 'via [$symbol$version]($style) '
symbol = "󰎙 "

[git_branch]
symbol = " "
style = "bold purple"

[git_state]
format = "[\\($state($progress_current of $progress_total)\\)]($style)"
cherry_pick = "[ PICKING](bold red)"

[git_status]
format = '([\[$ahead_behind\]]($style) )'
style = "bold blue"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[docker_context]
format = "in [$symbol$context]($style) "
symbol = " "

[terraform]
format = 'via [$symbol$version]($style) '
symbol = '󱁢 ' 
detect_files = ['.tflint.hcl','.terraform-version'] 

[cmd_duration]
style = 'bold italic yellow'
