" Automatically include Pathogen plugins
execute pathogen#infect()

" Set some sensible defaults
syntax enable
filetype plugin indent on
set colorcolumn=120
set number
set wrap
set linebreak
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set showmatch

" GUI customization
set background=dark
set guifont=Operator\ Mono\ Book:h14
let NERDTreeShowHidden=1
set noshowmode

" Set leader character
let mapleader=" "

" Custom commands
map <leader>s :source ~/.vimrc<cr>
nnoremap <Leader><Leader> :e#<CR>
nnoremap <Leader>r :CommandTFlush<CR>
nmap <leader>n :NERDTreeToggle<CR>
nmap <leader>j :NERDTreeFind<CR>

" NERDTree a little smarter
let NERDTreeMapActivateNode='<right>'
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']

" Set up Airline
let g:airline_theme='dark'
let g:airline#extensions#tabline#enabled = 1

" Keep more shit in RAM, bc it isn't 1987
set hidden
set history=100

" Strip whitespace on save
autocmd BufWritePre * :%s/\s\+$//e
