return {
	"sudo-tee/opencode.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		{
			"MeanderingProgrammer/render-markdown.nvim",
			opts = { anti_conceal = { enabled = false }, file_types = { "markdown", "opencode_output" } },
			ft = { "markdown", "Avante", "copilot-chat", "opencode_output" },
		},
		"saghen/blink.cmp",
		"folke/snacks.nvim",
	},
	opts = {
		preferred_picker = "snacks",
		preferred_completion = "blink",
		default_global_keymaps = true,
		-- 'build' or 'plan' or any custom configured. @see [OpenCode Agents](https://opencode.ai/docs/modes/)
		default_mode = "build",
		keymap_prefix = "<leader>o",
		keymap = {
			editor = {
				["<leader>og"] = { "toggle", desc = "Toggle OpenCode window" },
				["<leader>oi"] = { "open_input", desc = "Opens and focuses on input window on insert mode" },
				["<leader>oI"] = {
					"open_input_new_session",
					desc = "Opens and focuses on input window on insert mode. Creates a new session",
				},
				["<leader>oo"] = { "open_output", desc = "Opens and focuses on output window" },
				["<leader>ot"] = { "toggle_focus", desc = "Toggle focus between opencode and last window" },
				["<leader>oq"] = { "close", desc = "Close UI windows" },
				["<leader>os"] = { "select_session", desc = "Select and load a opencode session" },
				["<leader>op"] = { "configure_provider", desc = "Quick provider and model switch from predefined list" },
				["<leader>od"] = {
					"diff_open",
					desc = "Opens a diff tab of a modified file since the last opencode prompt",
				},
				["<leader>o]"] = { "diff_next", desc = "Navigate to next file diff" },
				["<leader>o["] = { "diff_prev", desc = "Navigate to previous file diff" },
				["<leader>oc"] = { "diff_close", desc = "Close diff view tab and return to normal editing" },
				["<leader>ora"] = {
					"diff_revert_all_last_prompt",
					desc = "Revert all file changes since the last opencode prompt",
				},
				["<leader>ort"] = {
					"diff_revert_this_last_prompt",
					desc = "Revert current file changes since the last opencode prompt",
				},
				["<leader>orA"] = {
					"diff_revert_all",
					desc = "Revert all file changes since the last opencode session",
				},
				["<leader>orT"] = {
					"diff_revert_this",
					desc = "Revert current file changes since the last opencode session",
				},
				["<leader>orr"] = { "diff_restore_snapshot_file", desc = "Restore a file to a restore point" },
				["<leader>orR"] = { "diff_restore_snapshot_all", desc = "Restore all files to a restore point" },
				["<leader>ox"] = { "swap_position", desc = "Swap Opencode pane left/right" },
				["<leader>opa"] = { "permission_accept", desc = "Accept permission request once" },
				["<leader>opA"] = { "permission_accept_all", desc = "Accept all (for current tool)" },
				["<leader>opd"] = { "permission_deny", desc = "Deny permission request once" },
			},
			input_window = {
				["<cr>"] = {
					"submit_input_prompt",
					mode = { "n", "i" },
					desc = "Submit prompt (normal mode and insert mode)",
				},
				["<esc>"] = { "close", desc = "Close UI windows" },
				["<C-c>"] = { "cancel", desc = "Cancel opencode request while it is running" },
				["~"] = {
					"mention_file",
					mode = "i",
					desc = "Pick a file and add to context. See File Mentions section",
				},
				["@"] = { "mention", mode = "i", desc = "Insert mention (file/agent)" },
				["/"] = { "slash_commands", mode = "i", desc = "Pick a command to run in the input window" },
				["#"] = {
					"context_items",
					mode = "i",
					desc = "Manage context items (current file, selection, diagnostics, mentioned files)",
				},
				["<C-i>"] = {
					"focus_input",
					mode = { "n", "i" },
					desc = "Focus on input window and enter insert mode at the end of the input from the output window",
				},
				["<tab>"] = { "toggle_pane", mode = { "n", "i" }, desc = "Toggle between input and output panes" },
				["<up>"] = {
					"prev_prompt_history",
					mode = { "n", "i" },
					desc = "Navigate to previous prompt in history",
				},
				["<down>"] = { "next_prompt_history", mode = { "n", "i" }, desc = "Navigate to next prompt in history" },
				["<M-m>"] = { "switch_mode", desc = "Switch between modes (build/plan)" },
			},
			output_window = {
				["<esc>"] = { "close", desc = "Close UI windows" },
				["<C-c>"] = { "cancel", desc = "Cancel opencode request while it is running" },
				["]]"] = { "next_message", desc = "Navigate to next message in the conversation" },
				["[["] = { "prev_message", desc = "Navigate to previous message in the conversation" },
				["<tab>"] = { "toggle_pane", mode = { "n", "i" }, desc = "Toggle between input and output panes" },
				["i"] = {
					"focus_input",
					"n",
					desc = "Focus on input window and enter insert mode at the end of the input from the output window",
				},
				["<leader>oS"] = { "select_child_session", desc = "Select and load a child session" },
				["<leader>oD"] = { "debug_message", desc = "Open raw message in new buffer for debugging" },
				["<leader>oO"] = { "debug_output", desc = "Open raw output in new buffer for debugging" },
				["<leader>ods"] = { "debug_session", desc = "Open raw session in new buffer for debugging" },
			},
			permission = {
				accept = "a",
				accept_all = "A",
				deny = "d",
			},
			session_picker = { delete_session = { "<C-d>" } },
		},
		ui = {
			position = "right",
			input_position = "bottom",
			window_width = 0.40,
			input_height = 0.20,
			display_model = true,
			display_context_size = true,
			display_cost = true,
			window_highlight = "Normal:OpencodeBackground,FloatBorder:OpencodeBorder",
			icons = {
				preset = "nerdfonts",
				overrides = {},
			},
			output = {
				tools = { show_output = true },
				rendering = {
					markdown_debounce_ms = 250,
					on_data_rendered = nil,
				},
			},
			input = { text = { wrap = true } },
			completion = {
				file_sources = {
					enabled = true,
					preferred_cli_tool = "server",
					ignore_patterns = {
						"^%.git/",
						"^%.svn/",
						"^%.hg/",
						"node_modules/",
						"%.pyc$",
						"%.o$",
						"%.obj$",
						"%.exe$",
						"%.dll$",
						"%.so$",
						"%.dylib$",
						"%.class$",
						"%.jar$",
						"%.war$",
						"%.ear$",
						"target/",
						"build/",
						"dist/",
						"out/",
						"deps/",
						"%.tmp$",
						"%.temp$",
						"%.log$",
						"%.cache$",
					},
					max_files = 10,
					max_display_length = 50,
				},
			},
		},
		context = {
			enabled = true,
			cursor_data = { enabled = false },
			diagnostics = {
				info = false,
				warn = true,
				error = true,
			},
			current_file = { enabled = true },
			selection = { enabled = true },
		},
		debug = { enabled = false },
		prompt_guard = nil,
	},
}
