#!/usr/bin/env sh

# NOTE: for this to work you must configure sudo such that it will be able to run the command without password
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#
# global settings
yabai -m config                                 \
    active_window_opacity        1.0            \
    auto_balance                 on             \
    focus_follows_mouse          off            \
    insert_feedback_color        0xffd75f5f     \
    mouse_follows_focus          off            \
    normal_window_opacity        0.90           \
    split_ratio                  0.50           \
    split_type                   auto           \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity               on             \
    window_opacity_duration      0.0            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_shadow                float          \
    window_zoom_persist          on             \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10

# rules
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|RingCentral Meetings|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor|MongoDB Compass|Plexamp)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# NOTE: get around spacing differences based on sketchybar / the notch...
NOTCH_UUID="1FFD8930-F1C9-5FB9-A0B6-45F2F0499C0B"
NORMAL_BAR=40
NOTCH_BAR=0

yabai -m signal --add event=display_added action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; else yabai -m config external_bar all:$NORMAL_BAR:0; fi"
yabai -m signal --add event=display_removed action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NOTCH_BAR:0; fi"

if [[ "$(yabai -m query --displays | jq '.[].uuid')" =~ "$NOTCH_UUID" ]]; then 
  if [ "$(yabai -m query --displays | jq length)" -gt "1" ]; then 
    yabai -m config external_bar main:$NORMAL_BAR:0; 
  else 
    yabai -m config external_bar all:$NOTCH_BAR:0; 
  fi 
else 
  yabai -m config external_bar all:$NORMAL_BAR:0; 
fi

# NOTE: Tweaks for Ghostty - more here: https://ghostty.org/docs/help/macos-tiling-wms#yabai
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

yabai -m config layout bsp
echo "yabai configuration loaded.."
