#!/bin/bash
ITEM_DIR="$HOME/.config/sketchybar/items" 
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" 
UTILS_DIR="$HOME/.config/sketchybar/utils"

# Load in color scheme
source "$UTILS_DIR/colors.sh"

bar=(
  position=top
  height=30
  blur_radius=30
  color=$BAR_BG
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$BLUE
  label.color=$TEXT
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# Left Side
source "$ITEM_DIR/spaces.sh"
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# Right Side
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

echo "sketchybar config loaded..."
