#!/bin/bash
FONT="Hack Nerd Font"
ICON_PADDING=4
LABEL_PADDING=2

ITEM_DIR="$HOME/.config/sketchybar/items" 
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" 
UTILS_DIR="$HOME/.config/sketchybar/utils"

source "$UTILS_DIR/colors.sh"
source "$UTILS_DIR/icons.sh"

bar=(
  blur_radius=30
  color=$BAR_BG
  height=33
  padding_left=5
  padding_right=5
  position=top
  topmost=window
)

sketchybar --bar "${bar[@]}"

default=(
  icon.color=$BLUE
  icon.font="$FONT:Bold:17.0"
  icon.padding_left=$ICON_PADDING
  icon.padding_right=$ICON_PADDING
 
  label.color=$TEXT
  label.font="$FONT:Bold:14.0"
  label.padding_left=$LABEL_PADDING
  label.padding_right=$LABEL_PADDING
 
  padding_left=5
  padding_right=5

  popup.background.border_color=$TEXT
  popup.background.border_width=2
  popup.background.color=$BAR_BG
  popup.background.corner_radius=9
  popup.background.shadow.drawing=on
  popup.blur_radius=20
)
sketchybar --default "${default[@]}"

# Left Side
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=on script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# Right Side
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

echo "sketchybar config loaded..."
